### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by vritser** [emacs-eaf/eaf-git#15]
When there is a SQLite db file in the project, the `get_line_info` function will report an error, I don't know how to handle with it better
<img width="1439" alt="UnicodeDecodeError" src="https://user-images.githubusercontent.com/16340478/163656624-4e4da06c-c4ec-4046-a664-463358244611.png">

**Comment by manateelazycat** [comment]
I will fix this issue later. ;)

**Comment by manateelazycat** [comment]
Has fixed, thanks for report.
