### ISSUE TITLE
安装好 eaf 和 eaf-git 后，使用 eaf-open-git 报错 “FileNotFoundError: [Errno 2] No such file or directory:”

### ISSUE THREAD

**Issue by patrolli** [emacs-eaf/eaf-git#30]
如题，在 *eaf* buffer 中的报错信息是：

"File "c:\Users\xxx\.emacs.d\site-lisp\emacs-application-framework\core\webengine.py", line 1487, in load_index_html
    with open(self.index_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:/Users/xxx/.emacs.d/site-lisp/emacs-application-framework/app/git\\dist\\index.html'"

![image](https://user-images.githubusercontent.com/25717445/173314030-a703579a-5034-4b53-80a4-35517877a3c2.png)

**Comment by patrolli** [comment]
这个问题解决了，eslint 的版本冲突了，参考：https://github.com/emacs-eaf/emacs-application-framework/issues/975#issuecomment-1146909088。但 eaf-open-git 打开后还是一片空白。。

**Comment by manateelazycat** [comment]
空白的问题最新版已经修复。
