### ISSUE TITLE
[RFC] Dashboard 展开/折叠（Expand / Collapse）

### ISSUE THREAD

**Issue by SuperMMX** [emacs-eaf/eaf-git#31]
这几天做了这样一个特性，和 Magit 一样，Dashboard 中每部分可以展开或者折叠，并可以设置每部分的初始状态。仍然是用 j/k 选择，本来想用 TAB 来展开或折叠，好像不起作用，只好改成了 E。

其中纵向布局中，上下两块高度不再固定，而是随着展开折叠会有变化。横向布局则不变。

最初的目的是因为经常会有一些其他文件在 untracked 中，不太方便在 .gitignoe 中忽略，但又不需要加入 git 中，所以缺省想隐藏这些文件，Magit 是可以展开、折叠的，很方便。

上图先看看：

![state-vertical](https://user-images.githubusercontent.com/4509679/174472984-b19d5530-22cc-41e0-bda7-76e8c2213982.png)
![state-horizotnal](https://user-images.githubusercontent.com/4509679/174472983-477ddd65-4479-4188-938e-933f88338571.png)

![state-vertical-2](https://user-images.githubusercontent.com/4509679/174472981-033f4ccb-80cb-4a48-97d7-4bb258d21ee1.png)
![state-horizotnal-2](https://user-images.githubusercontent.com/4509679/174472979-044fdcfe-f643-416f-89ef-289a9bbc2f75.png)

先忽略红色，是为了选择更显眼一些。

不知道其他人有没有这个需求，有的话我可以发 PR。

**Comment by manateelazycat** [comment]
看着可以呀，我正想说红色好丑，哈哈哈哈哈
