### ISSUE TITLE
No module named app

### ISSUE THREAD

**Issue by Mercurius-Lee** [emacs-eaf/eaf-git#35]
从commit：551d91ec4ed66a8a9f56e593d73f6e646f7f0089升级到最新版本，*eaf*报错，No module named app,   不能使用。回退版本后一切正常。

**Comment by manateelazycat** [comment]
不应该啊， 你最新版出错时 `*eaf*` buffer 是啥内容？

**Comment by Mercurius-Lee** [comment]
* 系统说明
操作系统： Mac OS 10.15.7
python: 系统内有原生python2/python3.8/python3.9/python3.10，前期中过无数坑，将系统python3 默认为python3.10,专门服务EAF.
node: v12.18.3 @vue/cli@4.5.13
EMACS: brew install emacs-plus@28 ( 28.2全屏fullscreen不兼容EAF,采用 toggle-frame-maximized )
EMACS-包管理器： straight.el
EAF安装插件：eaf-demo eaf-vue-demo eaf-browser eaf-pdf－viewer eaf-markdown-previewer eaf-git eaf-org-previewer eaf-rss-reader eaf-netease-cloud-music
EAF安装方法：参照 [[https://emacs-china.org/t/straight-eaf/19929][分享：使用 straight 安装 eaf 的思路 - Emacs-general - Emacs China]] 按照自己的系统情况将代码中的 python 调整为python3， pip3调整为pip3.10
#+begin_src emacs-lisp :tangle yes

(defun my-eaf-install-deps(app-dir)
  "Install deps from dependencies.json."
  (let* ((deps-dict (with-temp-buffer
                      (insert-file-contents (expand-file-name "dependencies.json" app-dir))
                      (json-parse-string (buffer-string))))
         (pip-deps (gethash "win32" (or (gethash "pip" deps-dict) (make-hash-table))))
         (vue-install (gethash "vue_install" deps-dict))
         (npm-install (gethash "npm_install" deps-dict))
         (npm-rebuild (gethash "npm_rebuild" deps-dict))
         (npm-cmd (if (memq system-type '(cygwin windows-nt ms-dos)) "npm.cmd" "npm")))
    (when pip-deps
      (dolist (pkg (append pip-deps nil))
        (message "%s" (shell-command-to-string (format "pip3.10 install %s" pkg)))))
    (when vue-install
      (let ((default-directory app-dir))
        (message "%s" (shell-command-to-string (format "%s install" npm-cmd)))
        (message "%s" (shell-command-to-string (format "%s run build" npm-cmd)))))
    (when npm-install
      (let ((default-directory app-dir))
        (message "%s" (shell-command-to-string (format "%s install" npm-cmd)))))
    (when npm-rebuild
      (let ((default-directory app-dir))
        (message "%s" (shell-command-to-string (format "%s rebuild" npm-cmd)))))))

(use-package eaf
  :straight (eaf :type git :host github :repo "emacs-eaf/emacs-application-framework"
                 :files ("*")
                 :post-build ("python3" "install-eaf.py" "--install-core-deps"))

(use-package eaf-demo
  :after (eaf)
  :straight (eaf-demo :type git :host github :repo "emacs-eaf/eaf-demo" :files ("*")))

(use-package eaf-vue-demo
  :after (eaf)
  :straight (eaf-vue-demo :type git :host github :repo "emacs-eaf/eaf-vue-demo" :files ("*")
                          :post-build (my-eaf-install-deps (straight--build-dir "eaf-vue-demo")) ))

(use-package eaf-browser
  :after (eaf)
  :straight (eaf-browser :type git :host github :repo "emacs-eaf/eaf-browser" :files ("*")
                         :post-build (my-eaf-install-deps (straight--build-dir "eaf-browser"))))

(use-package eaf-pdf-viewer
  :after (eaf)
  :straight (eaf-pdf-viewer :type git :host github :repo "emacs-eaf/eaf-pdf-viewer" :files ("*")
                            :post-build (my-eaf-install-deps (straight--build-dir "eaf-pdf-viewer"))))

(use-package eaf-markdown-previewer
  :after (eaf)
  :straight (eaf-markdown-previewer :type git :host github :repo "emacs-eaf/eaf-markdown-previewer" :files ("*")
                                    :post-build (my-eaf-install-deps (straight--build-dir "eaf-markdown-previewer"))))

(use-package eaf-git
  :after (eaf)
  :straight (eaf-git :type git :host github :repo "emacs-eaf/eaf-git" :files ("*")
                     :post-build (my-eaf-install-deps (straight--build-dir "eaf-git"))))

(use-package eaf-org-previewer
  :after (eaf)
  :straight (eaf-org-previewer :type git :host github :repo "emacs-eaf/eaf-org-previewer" :files ("*")
                     :post-build (my-eaf-install-deps (straight--build-dir "eaf-org-previewer"))))

(use-package eaf-rss-reader
  :disabled
  :after (eaf)
  :straight (eaf-rss-reader :type git :host github :repo "emacs-eaf/eaf-rss-reader" :files ("*")
                     :post-build (my-eaf-install-deps (straight--build-dir "eaf-rss-reader"))))

(use-package eaf-netease-cloud-music
  :disabled
  :after (eaf)
  :straight (eaf-netease-cloud-music :type git :host github :repo "emacs-eaf/eaf-netease-cloud-music" :files ("*")
                     :post-build (my-eaf-install-deps (straight--build-dir "eaf-netease-cloud-music"))))

#+end_src

EAF具体配置： 参照 matthewZMD 的配置。 使用use-package/feature 进行配置
* 文件结构
** repos
~/.emacs.d/straight/repos/
--------------------------emacs-application-framework/
--------------------------eaf-rss-reader/
--------------------------eaf-git/
--------------------------eaf-demo/
--------------------------eaf-vue-demo/
--------------------------eaf-browser/
--------------------------eaf-pdf-viewer/
--------------------------eaf-org-previewer/
--------------------------eaf-markdown-previewer/
--------------------------eaf-neteasecloud-music/
** build
~/.emacs.d/straight/build/
--------------------------eaf/
--------------------------eaf-rss-reader/
--------------------------eaf-git/
--------------------------eaf-demo/
--------------------------eaf-vue-demo/
--------------------------eaf-browser/
--------------------------eaf-pdf-viewer/
--------------------------eaf-org-previewer/
--------------------------eaf-markdown-previewer/
--------------------------eaf-neteasecloud-music/
* 截图
未升级前截图：
<img width="1666" alt="图片" src="https://user-images.githubusercontent.com/31580811/194861938-c02b6020-edec-4be0-b60a-45f964d3d794.png">
升级到最新commit:eca356afd00f8292b750c6fdcb42d339b1835296
不能打开git, eaf报错截图
<img width="1528" alt="图片" src="https://user-images.githubusercontent.com/31580811/194864631-7dcee2ad-0dc3-4866-ac7f-b11fe5a46f87.png">

**Comment by manateelazycat** [comment]
按照正常的 git clone 安装， eaf-git 应该在 eaf/app/ 目录下， 最终的效果是 eaf/app/eaf-git/buffer.py

**Comment by manateelazycat** [comment]
https://emacs-china.org/t/straight-eaf/19929 的安装方法肯定是不对的。

你应该正常执行：
```
git clone --depth=1 -b master https://github.com/emacs-eaf/emacs-application-framework.git ~/.emacs.d/site-lisp/emacs-application-framework/
```
和
```
cd emacs-application-framework
chmod +x ./install-eaf.py
./install-eaf.py
```
就可以自动安装， 不要用论坛那个方法， 那个方法导致一个应用下只要有多个模块， 都会报错的。

**Comment by Mercurius-Lee** [comment]
> https://emacs-china.org/t/straight-eaf/19929 的安装方法肯定是不对的。
> 
> 你应该正常执行：
> 
> ```
> git clone --depth=1 -b master https://github.com/emacs-eaf/emacs-application-framework.git ~/.emacs.d/site-lisp/emacs-application-framework/
> ```
> 
> 和
> 
> ```
> cd emacs-application-framework
> chmod +x ./install-eaf.py
> ./install-eaf.py
> ```
> 
> 就可以自动安装， 不要用论坛那个方法， 那个方法导致一个应用下只要有多个模块， 都会报错的。

谢谢大佬超快的回复！辛苦了！
straight.el 的安装包管理确实 跟EAF这块兼容性差，想要统一管理，还是要用您一贯推荐的方法，依靠一款包管理器行天下在Emacs中就是不现实的想法。straight.el + eaf-git-submodule 应该可以完美管理好emacs的包。
