### ISSUE TITLE
preview 的 diff 没有高亮

### ISSUE THREAD

**Issue by xhcoding** [emacs-eaf/eaf-git#41]
显示出来是这种效果

![image](https://user-images.githubusercontent.com/30917129/215656515-3e5c9e9d-11d2-4382-aebe-2630befd386c.png)

inspect 元素，发现有一些 css class 没有定义

![image](https://user-images.githubusercontent.com/30917129/215656801-5b39d3bb-c754-4049-a66b-ba74128d82ed.png)

**Comment by manateelazycat** [comment]
浅色主题的theme估计要重新选择

**Comment by manateelazycat** [comment]
eaf-git-delta-default-light-theme 这个变量要改一下，要看一下 pygments 的文档

**Comment by xhcoding** [comment]
在 https://pygments.org/styles/ 找个主题换一下就好了

```elisp
  (setq eaf-git-light-highlight-style "emacs")

```

**Comment by manateelazycat** [comment]
大佬，可以发个补丁，我也觉得默认浅色主题有问题，只是还没研究为什么。

**Comment by manateelazycat** [comment]
最新版默认浅色是 emacs 主题
